### ISSUE TITLE
the website search doesn't work

### ISSUE THREAD

**Issue by typhainepl** [iKurito/codnas-repeats#1]
Hi,
I tried using the codnas-repeat website https://codnas-repeats.bioinformatica.org/, but doing the search, I always obtain a `Result not found` message, no matter which PDB I use in the autocomplete suggestions.

**Comment by iKurito** [comment]
> Hi, I tried using the codnas-repeat website https://codnas-repeats.bioinformatica.org/, but doing the search, I always obtain a `Result not found` message, no matter which PDB I use in the autocomplete suggestions.

Hi,
Thank you for bringing the issue with searches on CODNAS-Repeats to my attention. I'm currently investigating the problem and will work on a solution. I'll keep you updated on my progress.

**Comment by iKurito** [comment]
> Hi, I tried using the codnas-repeat website https://codnas-repeats.bioinformatica.org/, but doing the search, I always obtain a `Result not found` message, no matter which PDB I use in the autocomplete suggestions.

Hi,
The issue with searches on CoDNaS-Repeats has been resolved. Feel free to revisit the site. Also, you might want to check out bioinformatica.org for more resources.

Best regards

**Comment by typhainepl** [comment]
Hi,
Thanks for fixing it. I am aware of the other resources (I work with Manuel) and Martin from Argentina is the one who told me about your tool ;)

**Comment by iKurito** [comment]
> Hi, Thanks for fixing it. I am aware of the other resources (I work with Manuel) and Martin from Argentina is the one who told me about your tool ;)

Yaaay! It's fantastic to hear you come recommended by Martín. Manuel is incredible at what he does, and Martín is a total crack in his field! Both are wonderful people, and I have a lot of respect and admiration for them. It would be an honor to work with you someday. I hope we stay in touch and see each other soon! c:
